--local lsp = require('mason_lspconfig').setup {};
--local capabilities = require('cmp_nvim_lsp').default_capabilities()
--
--vim.lsp.config("*", {
--  capabilities = capabilities,
--  on_attach = on_attach,
--})

-- Setup nvim-cmp
--local cmp = require("cmp")
--
--cmp.setup({
--  -- Enable LSP snippets
--  snippet = {
--    expand = function(args)
--      --require('luasnip').lsp_expand(args.body)
--      vim.fn["vsnip#anonymous"](args.body)
--    end,
--  },
--  mapping = cmp.mapping.preset.insert({
--    ['<C-k>'] = cmp.mapping.select_prev_item(),
--    ['<C-j>'] = cmp.mapping.select_next_item(),
--    ['<C-Space>'] = cmp.mapping.confirm({
--      behavior = cmp.ConfirmBehavior.Insert,
--      select = true
--    }),
--    ['<C-S-f>'] = cmp.mapping.scroll_docs(-4),
--    ['<C-f>'] = cmp.mapping.scroll_docs(4),
--  }),
--  window = {
--    completion = cmp.config.window.bordered(),
--    documentation = cmp.config.window.bordered(),
--  },
--  sources = {
--    { name = 'path' },                              -- file paths
--    { name = 'nvim_lsp', keyword_length = 3 },      -- from language server
--    { name = 'nvim_lsp_signature_help'},            -- display function signatures with current parameter emphasized
--    { name = 'nvim_lua', keyword_length = 2},       -- complete neovim's Lua runtime API such vim.lsp.*
--    { name = 'buffer', keyword_length = 2 },        -- source current buffer
--    { name = 'vsnip', keyword_length = 2 },         -- nvim-cmp source for vim-vsnip 
--    { name = 'calc'},                               -- source for math calculation
--  },
--  formatting = {
--    fields = {'menu', 'abbr', 'kind'},
--    format = function(entry, item)
--      local menu_icon = {
--        nvim_lsp = 'λ',
--        vsnip = '⋗',
--        buffer = 'Ω',
--        path = '🖫',
--      }
--      item.menu = menu_icon[entry.source.name]
--      return item
--    end,
--  },
--  preselect = 'item',
--  completion = {
--    completeopt = 'menu,menuone,noinsert'
--  }
--})
--
---- Configure diagnostic signs
--vim.diagnostic.config({
--  signs = {
--    text = {
--      [vim.diagnostic.severity.ERROR] = 'E',
--      [vim.diagnostic.severity.WARN] = 'W',
--      [vim.diagnostic.severity.HINT] = 'H',
--      [vim.diagnostic.severity.INFO] = 'I',
--    }
--  },
--  virtual_text = true,
--  update_in_insert = false,
--})
--
---- Common on_attach function for LSP servers
--
--LspAttach.on_attach.function(client, bufnr)
--  local opts = {buffer = bufnr, remap = false}
--
--  vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
--  vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
--  vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
--  vim.keymap.set("n", "<leader>vd", function() vim.diagnostic.open_float() end, opts)
--  vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
--  vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
--  vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
--  vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
--  vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
--  vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)
--end)

